-- Create Classes Table
create table public.classes (
  id bigint generated by default as identity primary key,
  title text not null,
  time text not null,
  duration text not null,
  studio text not null,
  age_range text not null,
  instructor jsonb not null, -- Stores { id, name, role, avatar }
  price numeric not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image text not null,
  badge text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Users Table (for admin authentication)
create table public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  role text not null default 'admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Contacts Table (for contact form submissions)
create table public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Sample Data (Optional)
insert into public.classes (title, time, duration, studio, age_range, instructor, price)
values 
  ('Lớp Ballet Cơ Bản', '08:30 AM', '60 MIN', 'Phòng A1', 'Trẻ em (4-6 tuổi)', '{"id": 1, "name": "Cô Minh Thư", "role": "Giám đốc chuyên môn", "avatar": "https://i.pravatar.cc/150?u=thu"}', 2000000),
  ('Kỹ thuật Pointe Nâng cao', '10:00 AM', '90 MIN', 'Phòng B2', 'Thiếu niên (12+)', '{"id": 2, "name": "Thầy Hoàng Nam", "role": "Biên đạo múa", "avatar": "https://i.pravatar.cc/150?u=nam"}', 3500000);

insert into public.products (name, price, image, badge)
values
  ('Giày Múa Satin Hồng', 450000, 'https://images.unsplash.com/photo-1517438476312-10d79c077509?q=80&w=800', 'NEW'),
  ('Váy Tutu Thiên Nga', 1200000, 'https://images.unsplash.com/photo-1547153760-18fc86324498?q=80&w=800', 'BEST SELLER'),
  ('Áo Leotard Chuyên Nghiệp', 650000, 'https://images.unsplash.com/photo-1620164368367-2708b5e90099?q=80&w=800', null);

-- Enable Row Level Security (RLS)
alter table public.classes enable row level security;
alter table public.products enable row level security;
alter table public.users enable row level security;
alter table public.contacts enable row level security;

-- Create Policy: Allow Public Read Access
create policy "Allow public read access on classes" on public.classes for select using (true);
create policy "Allow public read access on products" on public.products for select using (true);
create policy "Allow public read access on users" on public.users for select using (true);
create policy "Allow public read access on contacts" on public.contacts for select using (true);

-- Create Policy: Allow anon write access (MVP only)
create policy "Allow anon write access on classes" on public.classes for insert with check (true);
create policy "Allow anon update access on classes" on public.classes for update using (true);
create policy "Allow anon delete access on classes" on public.classes for delete using (true);

create policy "Allow anon write access on products" on public.products for insert with check (true);
create policy "Allow anon update access on products" on public.products for update using (true);
create policy "Allow anon delete access on products" on public.products for delete using (true);

create policy "Allow anon write access on users" on public.users for insert with check (true);
create policy "Allow anon update access on users" on public.users for update using (true);
create policy "Allow anon delete access on users" on public.users for delete using (true);

create policy "Allow anon write access on contacts" on public.contacts for insert with check (true);
create policy "Allow anon update access on contacts" on public.contacts for update using (true);
create policy "Allow anon delete access on contacts" on public.contacts for delete using (true);

-- Create Orders Table (for payment tracking)
create table public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  shipping_address text,
  shipping_fee numeric default 0,
  shipping_platform text,
  shipping_service text,
  item_name text not null,
  amount numeric not null,
  status text not null default 'pending', -- pending, completed, cancelled
  order_code text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.orders enable row level security;
create policy "Allow public read access on orders" on public.orders for select using (true);
create policy "Allow anon write access on orders" on public.orders for insert with check (true);
create policy "Allow anon update access on orders" on public.orders for update using (true);
create policy "Allow anon delete access on orders" on public.orders for delete using (true);

-- Create Settings Table
create table public.settings (
  key text primary key,
  value text not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.settings enable row level security;
create policy "Allow public read access on settings" on public.settings for select using (true);
create policy "Allow anon update access on settings" on public.settings for update using (true);
create policy "Allow anon insert access on settings" on public.settings for insert with check (true);

-- Insert Default Settings
insert into public.settings (key, value)
values 
  ('site_name', 'Dance House'),
  ('site_logo', 'https://dancehouse.vn/logo.png'),
  ('contact_phone', '090 123 4567'),
  ('contact_email', 'hello@dancehouse.vn'),
  ('contact_address', '123 Đường Bà Huyện Thanh Quan, Quận 3, TP.HCM'),
  ('header_image', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=2000'),
  ('facebook_url', 'https://facebook.com/dancehouse'),
  ('instagram_url', 'https://instagram.com/dancehouse'),
  ('google_maps_link', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.4602324283!2d106.6781!3d10.7761');

-- Phase 1: Operational Excellence (CRM & Booking)

-- 1. Students Table
create table public.students (
  id uuid default gen_random_uuid() primary key,
  full_name text not null,
  email text,
  phone text,
  birthdate date,
  gender text,
  level text default 'Beginner',
  parent_name text,
  emergency_contact text,
  medical_note text,
  avatar_url text,
  join_date date default current_date,
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.students enable row level security;
create policy "Allow internal read for authenticated" on public.students for select using (auth.role() = 'authenticated');
create policy "Allow internal modify for authenticated" on public.students for all using (auth.role() = 'authenticated');

-- 2. Memberships Table
create table public.memberships (
  id uuid default gen_random_uuid() primary key,
  student_id uuid references public.students(id) on delete cascade not null,
  package_name text not null,
  total_sessions int not null,
  remaining_sessions int not null,
  start_date date not null,
  end_date date,
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.memberships enable row level security;
create policy "Allow internal read memberships" on public.memberships for select using (auth.role() = 'authenticated');
create policy "Allow internal modify memberships" on public.memberships for all using (auth.role() = 'authenticated');

-- 3. Attendance Table
create table public.attendance (
  id uuid default gen_random_uuid() primary key,
  student_id uuid references public.students(id) on delete cascade not null,
  class_id bigint references public.classes(id) on delete cascade,
  date date default current_date not null,
  check_in_time timestamp with time zone default timezone('utc'::text, now()),
  status text default 'Present',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.attendance enable row level security;
create policy "Allow internal read attendance" on public.attendance for select using (auth.role() = 'authenticated');
create policy "Allow internal modify attendance" on public.attendance for all using (auth.role() = 'authenticated');

-- Phase 2: Payment Automation

-- 1. Packages Table (Public membership packages for sale)
create table public.packages (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  description text,
  duration_days int,
  total_sessions int not null,
  price numeric not null,
  is_active boolean default true,
  display_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.packages enable row level security;
create policy "Allow public read packages" on public.packages for select using (is_active = true);
create policy "Allow authenticated all on packages" on public.packages for all using (auth.role() = 'authenticated');

-- Insert default packages
insert into public.packages (name, description, duration_days, total_sessions, price, display_order)
values 
  ('Gói Tháng', 'Lý tưởng cho học viên mới bắt đầu', 30, 8, 2000000, 1),
  ('Gói Quý', 'Tiết kiệm 15% so với gói tháng', 90, 24, 5100000, 2),
  ('Gói Năm', 'Ưu đãi tốt nhất - Tiết kiệm 20%', 365, 96, 19200000, 3),
  ('Gói 10 buổi', 'Linh hoạt, không giới hạn thời gian', null, 10, 2500000, 4);

-- 2. Transactions Table
create table public.transactions (
  id uuid default gen_random_uuid() primary key,
  order_code text unique not null,
  student_id uuid references public.students(id) on delete set null,
  package_id uuid references public.packages(id) on delete set null,
  customer_name text not null,
  customer_email text,
  customer_phone text not null,
  amount numeric not null,
  payment_gateway text default 'payos',
  transaction_code text,
  status text default 'pending',
  payment_url text,
  paid_at timestamp with time zone,
  metadata jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.transactions enable row level security;
create policy "Allow public insert transactions" on public.transactions for insert with check (true);
create policy "Allow authenticated all on transactions" on public.transactions for all using (auth.role() = 'authenticated');

-- Enable pgcrypto for password hashing
create extension if not exists pgcrypto;

-- 1. Students Table
create table public.students (
  id uuid default gen_random_uuid() primary key,
  full_name text not null,
  phone text unique not null,
  email text,
  guardian_name text,
  guardian_phone text,
  dob date,
  password text, -- Hashed password
  status text default 'Active', -- Active, Inactive, Graduated
  join_date date default now(),
  avatar_url text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Secure Login Function
create or replace function public.student_login(phone_input text, password_input text)
returns json as $$
declare
  found_student public.students;
begin
  select * into found_student
  from public.students
  where phone = phone_input;

  if found_student is null then
    return null;
  end if;

  if found_student.password = crypt(password_input, found_student.password) then
    return row_to_json(found_student);
  else
    return null;
  end if;
end;
$$ language plpgsql security definer;

-- Set Student Password Function (Admin only)
create or replace function public.set_student_password(student_id uuid, new_password text)
returns void as $$
begin
  update public.students
  set password = crypt(new_password, gen_salt('bf'))
  where id = student_id;
end;
$$ language plpgsql security definer;

-- 3. News Table
create table public.news (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  content text not null,
  summary text,
  image_url text,
  is_visible boolean default true,
  published_at timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.news enable row level security;
create policy "Allow public read news" on public.news for select using (true);
create policy "Allow authenticated all on news" on public.news for all using (auth.role() = 'authenticated');

-- 4. Reporting RPCs
create or replace function public.get_monthly_revenue()
returns table (
  month int,
  year int,
  total_revenue bigint,
  transaction_count bigint
) as $$
begin
  return query
  select 
    extract(month from created_at)::int as month,
    extract(year from created_at)::int as year,
    sum(amount)::bigint as total_revenue,
    count(*)::bigint as transaction_count
  from public.transactions
  where status = 'completed'
  group by year, month
  order by year desc, month desc;
end;
$$ language plpgsql security definer;

-- 5. Marketing Automation RPCs
create or replace function public.get_expiring_memberships()
returns table (
  student_name text,
  phone text,
  package_name text,
  end_date date,
  days_left int
) as $$
begin
  return query
  select 
    s.full_name as student_name,
    s.phone,
    p.name as package_name,
    m.end_date,
    (m.end_date - current_date)::int as days_left
  from public.memberships m
  join public.students s on m.student_id = s.id
  join public.products p on m.package_id = p.id
  where m.status = 'Active'
  and m.end_date between current_date and (current_date + interval '7 days')
  order by m.end_date asc;
end;
$$ language plpgsql security definer;

-- 6. Lead Management (Trial Bookings)
create table public.trial_bookings (
  id uuid default gen_random_uuid() primary key,
  full_name text not null,
  phone text not null,
  email text,
  class_interest text,
  note text,
  status text default 'Pending', -- Pending, Contacted, Converted, Cancelled
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.trial_bookings enable row level security;

-- Allow public to insert (register)
create policy "Allow public insert trial_bookings" on public.trial_bookings for insert with check (true);

-- Allow authenticated (admin) to view and update
create policy "Allow authenticated all on trial_bookings" on public.trial_bookings for all using (auth.role() = 'authenticated');
