-- Create Classes Table
create table public.classes (
  id bigint generated by default as identity primary key,
  title text not null,
  time text not null,
  duration text not null,
  studio text not null,
  age_range text not null,
  instructor jsonb not null, -- Stores { id, name, role, avatar }
  price numeric not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image text not null,
  badge text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Users Table (for admin authentication)
create table public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  role text not null default 'admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Contacts Table (for contact form submissions)
create table public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Sample Data (Optional)
insert into public.classes (title, time, duration, studio, age_range, instructor, price)
values 
  ('Lớp Ballet Cơ Bản', '08:30 AM', '60 MIN', 'Phòng A1', 'Trẻ em (4-6 tuổi)', '{"id": 1, "name": "Cô Minh Thư", "role": "Giám đốc chuyên môn", "avatar": "https://i.pravatar.cc/150?u=thu"}', 2000000),
  ('Kỹ thuật Pointe Nâng cao', '10:00 AM', '90 MIN', 'Phòng B2', 'Thiếu niên (12+)', '{"id": 2, "name": "Thầy Hoàng Nam", "role": "Biên đạo múa", "avatar": "https://i.pravatar.cc/150?u=nam"}', 3500000);

insert into public.products (name, price, image, badge)
values
  ('Giày Múa Satin Hồng', 450000, 'https://images.unsplash.com/photo-1517438476312-10d79c077509?q=80&w=800', 'NEW'),
  ('Váy Tutu Thiên Nga', 1200000, 'https://images.unsplash.com/photo-1547153760-18fc86324498?q=80&w=800', 'BEST SELLER'),
  ('Áo Leotard Chuyên Nghiệp', 650000, 'https://images.unsplash.com/photo-1620164368367-2708b5e90099?q=80&w=800', null);

-- Enable Row Level Security (RLS)
alter table public.classes enable row level security;
alter table public.products enable row level security;
alter table public.users enable row level security;
alter table public.contacts enable row level security;

-- Create Policy: Allow Public Read Access
create policy "Allow public read access on classes" on public.classes for select using (true);
create policy "Allow public read access on products" on public.products for select using (true);
create policy "Allow public read access on users" on public.users for select using (true);
create policy "Allow public read access on contacts" on public.contacts for select using (true);

-- Create Policy: Allow anon write access (MVP only)
create policy "Allow anon write access on classes" on public.classes for insert with check (true);
create policy "Allow anon update access on classes" on public.classes for update using (true);
create policy "Allow anon delete access on classes" on public.classes for delete using (true);

create policy "Allow anon write access on products" on public.products for insert with check (true);
create policy "Allow anon update access on products" on public.products for update using (true);
create policy "Allow anon delete access on products" on public.products for delete using (true);

create policy "Allow anon write access on users" on public.users for insert with check (true);
create policy "Allow anon update access on users" on public.users for update using (true);
create policy "Allow anon delete access on users" on public.users for delete using (true);

create policy "Allow anon write access on contacts" on public.contacts for insert with check (true);
create policy "Allow anon update access on contacts" on public.contacts for update using (true);
create policy "Allow anon delete access on contacts" on public.contacts for delete using (true);

-- Create Orders Table (for payment tracking)
create table public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_email text not null,
  item_name text not null,
  amount numeric not null,
  status text not null default 'pending', -- pending, completed, cancelled
  order_code text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.orders enable row level security;
create policy "Allow public read access on orders" on public.orders for select using (true);
create policy "Allow anon write access on orders" on public.orders for insert with check (true);
create policy "Allow anon update access on orders" on public.orders for update using (true);
create policy "Allow anon delete access on orders" on public.orders for delete using (true);
